### ISSUE TITLE
Build from Source(a whole bunch of installation issues)

### ISSUE THREAD

**Issue by acelufei** [alibaba/BladeDISC#384]
I build from source according the following rules : https://github.com/alibaba/BladeDISC/blob/main/docs/build_from_source.md,and I'm having a whole bunch of installation issues(bazel),is there any problem with your docker images?

**Comment by qiuxiafei** [comment]
Pls provide more information about your settings and also the error messages.

**Comment by acelufei** [comment]
the env is build from docker images : bladedisc/bladedisc latest-devel-cuda11.0
i enter the command as folows : cd pytorch_blade && bash ./ci_build/build_pytorch_blade.sh
and the problem :
DO TORCH_BLADE CI_BUILD
2022-06-11 08:05:39,778     INFO configuring tao_compiler ......
2022-06-11 08:05:39,778     INFO Execute shell command: `rm -rf tf_community/tensorflow/compiler/decoupling && ln -s /home/BladeDISC/tao_compiler/decoupling tf_community/tensorflow/compiler/decoupling`, cwd: /home/BladeDISC
2022-06-11 08:05:39,785     INFO Execute shell command: `rm -rf tf_community/tensorflow/compiler/mlir/disc && ln -s /home/BladeDISC/tao_compiler/mlir/disc tf_community/tensorflow/compiler/mlir/disc`, cwd: /home/BladeDISC
2022-06-11 08:05:39,795     INFO Execute shell command: `rm -rf tf_community/tensorflow/compiler/mlir/xla/ral && ln -s /home/BladeDISC/tao_compiler/mlir/xla/ral tf_community/tensorflow/compiler/mlir/xla/ral`, cwd: /home/BladeDISC
2022-06-11 08:05:39,801     INFO Execute shell command: `rm -rf tf_community/tensorflow/../.bazelrc.user && ln -s /home/BladeDISC/tao_compiler/.bazelrc.user tf_community/tensorflow/../.bazelrc.user`, cwd: /home/BladeDISC
2022-06-11 08:05:39,806     INFO linking ./tao to tf_community/tao
2022-06-11 08:05:39,806     INFO Execute shell command: `rm -rf tf_community/tao && ln -s /home/BladeDISC/tao tf_community/tao`, cwd: /home/BladeDISC
__version__ = '0.2.0+1.7.1.cu110'
__serialization_version__ = '0.0.3'
debug = False
cuda = '11.0'
cuda_available = True
build_tensorrt = True
static_tensorrt = False
git_version = '8bbb8559cfedd4402ad159b2a6d80e79c06ded56'
torch_version = '1.7.1+cu110'
torch_git_version = '57bffc3a8e4fee0cce31e1ff1f662ccf7b16db57'
GLIBCXX_USE_CXX11_ABI = False

running develop
/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
running egg_info
writing torch_blade.egg-info/PKG-INFO
writing dependency_links to torch_blade.egg-info/dependency_links.txt
writing requirements to torch_blade.egg-info/requires.txt
writing top-level names to torch_blade.egg-info/top_level.txt
reading manifest file 'torch_blade.egg-info/SOURCES.txt'
writing manifest file 'torch_blade.egg-info/SOURCES.txt'
running build_ext
__version__ = '0.2.0+1.7.1.cu110'
__serialization_version__ = '0.0.3'
debug = False
cuda = '11.0'
cuda_available = True
build_tensorrt = True
static_tensorrt = False
git_version = '8bbb8559cfedd4402ad159b2a6d80e79c06ded56'
torch_version = '1.7.1+cu110'
torch_git_version = '57bffc3a8e4fee0cce31e1ff1f662ccf7b16db57'
GLIBCXX_USE_CXX11_ABI = False

Starting local Bazel server and connecting to it...
ERROR: Config value 'cuda' is not defined in any .rc file
INFO: Invocation ID: 5165b577-2b40-4323-8dcb-49defde3e0c9
Traceback (most recent call last):
  File "setup.py", line 154, in <module>
    zip_safe=False,
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 71, in run
    build.run(extdir=extdir, srcdir=ext.sourcedir, build_temp="build/temp")
  File "/home/BladeDISC/pytorch_blade/bazel_build.py", line 144, in run
    subprocess.check_call(bazel_disc_build_cmd, shell=True, env=env, executable="/bin/bash")
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -e; set -o pipefail;  source .bazel_pyenv/bin/activate; bazel build --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env BAZEL_LINKLIBS=-lstdc++ --action_env CC=/usr/bin/gcc --action_env CXX=/usr/bin/g++ --config=torch_cxx11abi_0 --config=torch_cuda --compilation_mode=opt @org_tensorflow//tensorflow/compiler/mlir/disc:disc_compiler_main' returned non-zero exit status 2.

**Comment by fortianyou** [comment]
> ERROR: Config value 'cuda' is not defined in any .rc file

The error is raised because of a 'cuda' config in any .rc file. Do you have updated the submodule? Try rebuilding the after successful executing the following command:
```
git submodule update --init --recursive
```
