### ISSUE TITLE
Inconsistent CUDA toolkit path: /usr vs /usr/lib

### ISSUE THREAD

**Issue by justlike-prog** [alibaba/BladeDISC#401]
Hi, when building from scratch I get the issue "Inconsistent CUDA toolkit path: /usr vs /usr/lib". Here is the relevant part of the log:

Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Invocation ID: 5eeb5bb3-e464-475f-b413-d0aa08b98c4e
INFO: Reading 'startup' options from /home/metcon/work/BladeDISC/pytorch_blade/.bazelrc: --host_jvm_args=-Djdk.http.auth.tunneling.disabledSchemes=
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=203
INFO: Reading rc options for 'build' from /home/metcon/work/BladeDISC/tf_community/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/metcon/work/BladeDISC/tf_community/.bazelrc:
  'build' options: --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=true --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Reading rc options for 'build' from /home/metcon/work/BladeDISC/pytorch_blade/.bazelrc:
  'build' options: --disk_cache=~/.cache --define is_torch_disc=true
INFO: Found applicable config definition build:short_logs in file /home/metcon/work/BladeDISC/tf_community/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/metcon/work/BladeDISC/tf_community/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:torch_cxx11abi_0 in file /home/metcon/work/BladeDISC/pytorch_blade/.bazelrc: --config=cxx11abi_0 --action_env IF_CXX11_ABI=0
INFO: Found applicable config definition build:cxx11abi_0 in file /home/metcon/work/BladeDISC/tao_compiler/.bazelrc.user: --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0
INFO: Found applicable config definition build:torch_cuda in file /home/metcon/work/BladeDISC/pytorch_blade/.bazelrc: --config=cuda --config=disc_cuda --define enable_cuda=true
INFO: Found applicable config definition build:cuda in file /home/metcon/work/BladeDISC/tf_community/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:disc_cuda in file /home/metcon/work/BladeDISC/tao_compiler/.bazelrc.user: --config=disc --config=cuda
INFO: Found applicable config definition build:disc in file /home/metcon/work/BladeDISC/tao_compiler/.bazelrc.user: --define framework_shared_object=false --experimental_multi_threaded_digest
INFO: Found applicable config definition build:cuda in file /home/metcon/work/BladeDISC/tf_community/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:linux in file /home/metcon/work/BladeDISC/tf_community/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /home/metcon/work/BladeDISC/tf_community/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/92c0bd2786449fcfa6abee89b306843550b39c5a.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
DEBUG: /home/metcon/.cache/bazel/_bazel_metcon/7e3d553b63a714857697b0fdb9a4243d/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /home/metcon/.cache/bazel/_bazel_metcon/7e3d553b63a714857697b0fdb9a4243d/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /home/metcon/.cache/bazel/_bazel_metcon/7e3d553b63a714857697b0fdb9a4243d/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Repository local_config_cuda instantiated at:
  /home/metcon/work/BladeDISC/pytorch_blade/WORKSPACE:142:14: in <toplevel>
  /home/metcon/.cache/bazel/_bazel_metcon/7e3d553b63a714857697b0fdb9a4243d/external/org_tensorflow/tensorflow/workspace2.bzl:869:19: in workspace
  /home/metcon/.cache/bazel/_bazel_metcon/7e3d553b63a714857697b0fdb9a4243d/external/org_tensorflow/tensorflow/workspace2.bzl:95:19: in _tf_toolchains
Repository rule cuda_configure defined at:
  /home/metcon/.cache/bazel/_bazel_metcon/7e3d553b63a714857697b0fdb9a4243d/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:1489:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
	File "/home/metcon/.cache/bazel/_bazel_metcon/7e3d553b63a714857697b0fdb9a4243d/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1442, column 38, in _cuda_autoconf_impl
		_create_local_cuda_repository(repository_ctx)
	File "/home/metcon/.cache/bazel/_bazel_metcon/7e3d553b63a714857697b0fdb9a4243d/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 981, column 35, in _create_local_cuda_repository
		cuda_config = _get_cuda_config(repository_ctx, find_cuda_config_script)
	File "/home/metcon/.cache/bazel/_bazel_metcon/7e3d553b63a714857697b0fdb9a4243d/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 668, column 30, in _get_cuda_config
		config = find_cuda_config(repository_ctx, find_cuda_config_script, ["cuda", "cudnn"])
	File "/home/metcon/.cache/bazel/_bazel_metcon/7e3d553b63a714857697b0fdb9a4243d/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 645, column 41, in find_cuda_config
		exec_result = _exec_find_cuda_config(repository_ctx, script_path, cuda_libraries)
	File "/home/metcon/.cache/bazel/_bazel_metcon/7e3d553b63a714857697b0fdb9a4243d/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 639, column 19, in _exec_find_cuda_config
		return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])
	File "/home/metcon/.cache/bazel/_bazel_metcon/7e3d553b63a714857697b0fdb9a4243d/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
		fail(
Error in fail: Repository command failed
Inconsistent CUDA toolkit path: /usr vs /usr/lib
ERROR: /home/metcon/work/BladeDISC/pytorch_blade/WORKSPACE:142:14: fetching cuda_configure rule //external:local_config_cuda: Traceback (most recent call last):
	File "/home/metcon/.cache/bazel/_bazel_metcon/7e3d553b63a714857697b0fdb9a4243d/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1442, column 38, in _cuda_autoconf_impl
		_create_local_cuda_repository(repository_ctx)
	File "/home/metcon/.cache/bazel/_bazel_metcon/7e3d553b63a714857697b0fdb9a4243d/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 981, column 35, in _create_local_cuda_repository
		cuda_config = _get_cuda_config(repository_ctx, find_cuda_config_script)
	File "/home/metcon/.cache/bazel/_bazel_metcon/7e3d553b63a714857697b0fdb9a4243d/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 668, column 30, in _get_cuda_config
		config = find_cuda_config(repository_ctx, find_cuda_config_script, ["cuda", "cudnn"])
	File "/home/metcon/.cache/bazel/_bazel_metcon/7e3d553b63a714857697b0fdb9a4243d/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 645, column 41, in find_cuda_config
		exec_result = _exec_find_cuda_config(repository_ctx, script_path, cuda_libraries)
	File "/home/metcon/.cache/bazel/_bazel_metcon/7e3d553b63a714857697b0fdb9a4243d/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 639, column 19, in _exec_find_cuda_config
		return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])
	File "/home/metcon/.cache/bazel/_bazel_metcon/7e3d553b63a714857697b0fdb9a4243d/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
		fail(
Error in fail: Repository command failed
Inconsistent CUDA toolkit path: /usr vs /usr/lib
INFO: Found applicable config definition build:cuda in file /home/metcon/work/BladeDISC/tf_community/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:cuda in file /home/metcon/work/BladeDISC/tf_community/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Invocation ID: 5eeb5bb3-e464-475f-b413-d0aa08b98c4e
ERROR: @local_config_cuda//:enable_cuda :: Error loading option @local_config_cuda//:enable_cuda: Repository command failed
Inconsistent CUDA toolkit path: /usr vs /usr/lib

Traceback (most recent call last):
  File "setup.py", line 137, in <module>
    setup(
  File "/home/metcon/anaconda3/envs/myenv/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/metcon/anaconda3/envs/myenv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/metcon/anaconda3/envs/myenv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/metcon/anaconda3/envs/myenv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/metcon/anaconda3/envs/myenv/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/metcon/anaconda3/envs/myenv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/metcon/anaconda3/envs/myenv/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/metcon/anaconda3/envs/myenv/lib/python3.8/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/home/metcon/anaconda3/envs/myenv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/metcon/anaconda3/envs/myenv/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/metcon/anaconda3/envs/myenv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "setup.py", line 71, in run
    build.run(extdir=extdir, srcdir=ext.sourcedir, build_temp="build/temp")
  File "/home/metcon/work/BladeDISC/pytorch_blade/bazel_build.py", line 144, in run
    subprocess.check_call(bazel_disc_build_cmd, shell=True, env=env, executable="/bin/bash")
  File "/home/metcon/anaconda3/envs/myenv/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -e; set -o pipefail;  source .bazel_pyenv/bin/activate; bazel build --action_env PYTHON_BIN_PATH=/home/metcon/anaconda3/envs/myenv/bin/python3 --action_env BAZEL_LINKLIBS=-lstdc++ --action_env CC=/usr/bin/gcc --action_env CXX=/usr/bin/g++ --config=torch_cxx11abi_0 --config=torch_cuda --compilation_mode=opt @org_tensorflow//tensorflow/compiler/mlir/disc:disc_compiler_main' returned non-zero exit status 2.

**Comment by qiuxiafei** [comment]
Pls take a look at: https://github.com/tensorflow/tensorflow/blob/cbd5590c952f7333276da41a6a0bb53ee8ae434e/third_party/gpus/find_cuda_config.py#L297
It seem that you have inconsistent CUDA installation in your environment. More specifically, your `nvcc` is under `/usr` (maybe `/usr/bin` or `/usr/local/cuda/bin`) while your nnvm (the `libdevice*.10.bc` file) is somewhere under `/usr/lib`. The suggestion is to double check packages installed or start one with `nvidia/cuda` docker image or reinstall CUDA from a clean environment.

**Comment by justlike-prog** [comment]
The installation was done from a clean environment.

**Comment by qiuxiafei** [comment]
Close as no updates, feel free to reopen.
