### ISSUE TITLE
mlir_disc_builder.so needed by libtorch_blade.so is missing

### ISSUE THREAD

**Issue by jues** [alibaba/BladeDISC#87]
Hi, I followed the doc for building bladeDISC for pytorch users, [build_from_source](https://alibaba.github.io/BladeDISC/docs/build_from_source.html) but there's an error occured.
```
ninja: error: '/disc/tf_community/bazel-bin/tensorflow/compiler/mlir/disc/mlir_disc_builder.so', needed by '../../torch_blade/libtorch_blade.so', missing and no known rule to make it
Traceback (most recent call last):
  File "setup.py", line 135, in <module>
    zip_safe=False,
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 36, in run
    self.install_for_development()
  File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 73, in run
    build_temp="build/temp")
  File "/disc/pytorch_blade/cmake_build.py", line 127, in run
    self.build_extension(extdir, srcdir, build_temp)
  File "/disc/pytorch_blade/cmake_build.py", line 197, in build_extension
    ["cmake", "--build", "."] + build_args, cwd=build_temp, env=env
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--target', 'package', '--', '-j72']' returned non-zero exit status 1.
```

**Comment by linearhit** [comment]
hi, something should be wrong when building mlir_disc_builder.so. Could you grep 'mlir_disc_builder.so' in the log and paste us what happened?
