### ISSUE TITLE
building error for pytorch

### ISSUE THREAD

**Issue by johnzlli** [alibaba/BladeDISC#995]
**Describe the bug**
when building bladedisc for pytorch，I met the error "ln: failed to create symbolic link '/disc/tf_community/tao/blade_gemm': No such file or directory".
 more details:
2023-02-06 11:22:08,691     INFO Execute shell command: `rm -rf tf_community/.tf_configure.bazelrc`, cwd: /disc
2023-02-06 11:22:08,727     INFO linking via tao_compiler/file_map ...
2023-02-06 11:22:08,728     INFO Execute shell command: `rm -rf /disc/tf_community/tensorflow/compiler/decoupling && ln -s /disc/tao_compiler/decoupling /disc/tf_community/tensorflow/compiler/decoupling`, cwd: /disc/pytorch_blade
2023-02-06 11:22:08,847     INFO Execute shell command: `rm -rf /disc/tf_community/tensorflow/compiler/mlir/disc && ln -s /disc/tao_compiler/mlir/disc /disc/tf_community/tensorflow/compiler/mlir/disc`, cwd: /disc/pytorch_blade
2023-02-06 11:22:08,852     INFO Execute shell command: `rm -rf /disc/tf_community/mlir/util && ln -s /disc/tao_compiler/mlir/util /disc/tf_community/mlir/util`, cwd: /disc/pytorch_blade
2023-02-06 11:22:08,858     INFO Execute shell command: `rm -rf /disc/tf_community/tensorflow/compiler/mlir/xla/ral && ln -s /disc/tao_compiler/mlir/xla/ral /disc/tf_community/tensorflow/compiler/mlir/xla/ral`, cwd: /disc/pytorch_blade
2023-02-06 11:22:08,863     INFO Execute shell command: `rm -rf /disc/tf_community/tensorflow/../.bazelrc.user && ln -s /disc/tao_compiler/.bazelrc.user /disc/tf_community/tensorflow/../.bazelrc.user`, cwd: /disc/pytorch_blade
2023-02-06 11:22:08,868     INFO linking ./tao to tao_compiler/tao
2023-02-06 11:22:08,869     INFO Execute shell command: `rm -rf /disc/tao_compiler/tao && ln -s /disc/tao /disc/tao_compiler/tao`, cwd: /disc/pytorch_blade
2023-02-06 11:22:08,874     INFO linking blade_gemm
2023-02-06 11:22:08,874     INFO Execute shell command: `rm -rf /disc/tf_community/tao/blade_gemm && ln -s /disc/../platform_alibaba/blade_gemm /disc/tf_community/tao/blade_gemm`, cwd: /disc/pytorch_blade
ln: failed to create symbolic link '/disc/tf_community/tao/blade_gemm': No such file or directory
Traceback (most recent call last):
  File "../scripts/python/common_setup.py", line 765, in <module>
    symlink_disc_files(args)
  File "../scripts/python/common_setup.py", line 623, in symlink_disc_files
    link_dirs(os.path.join(get_source_root_dir(), 'tf_community', 'tao', 'blade_gemm'),
  File "../scripts/python/common_setup.py", line 538, in link_dirs
    execute("rm -rf {0} && ln -s {1} {0}".format(dst_dir, src_dir))
  File "../scripts/python/common_setup.py", line 150, in execute
    subprocess.check_call(shell_setting + cmd, shell=True, executable="/bin/bash")
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -e; set -o pipefail; rm -rf /disc/tf_community/tao/blade_gemm && ln -s /disc/../platform_alibaba/blade_gemm /disc/tf_community/tao/blade_gemm' returned non-zero exit status 1.

**To Reproduce**
build pytorch_blade, just following the guide (https://github.com/alibaba/BladeDISC/blob/main/docs/build_from_source.md#building-bladedisc-for-pytorch-users)

**Example code**
If the code is too long (hopefully, it isn't), feel free to put it in a public gist and link it to the issue: https://gist.github.com.

**Expected behavior**

**Additional context for PyTorch**
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python3 collect_env.py
```

**Comment by tanyokwok** [comment]
@Yancey1989 Could you have a look at this issue? I also counter the problem. I think this might be related to the PR https://github.com/alibaba/BladeDISC/pull/972

**Comment by Yancey1989** [comment]
Thanks for your report, I will take a look at this issue and fix it ASAP.

**Comment by alanguo1234** [comment]
meet the same error

**Comment by Yancey1989** [comment]
Hi @alanguo1234 @johnzlli , can you rebase to the latest code and try again? #1002 fixed this error.

**Comment by johnzlli** [comment]
> Hi @alanguo1234 @johnzlli , can you rebase to the latest code and try again? #1002 fixed this error.
there is a new error....

2023-02-13 03:54:02,488     INFO Execute shell command: `rm -rf /disc/BladeDISC/tao/tao_bridge/gpu`, cwd: /disc/BladeDISC/pytorch_blade
__version__ = '0.2.0+1.7.1.cu110'
__serialization_version__ = '0.0.3'
debug = True
cuda = '11.0'
cuda_available = True
build_tensorrt = True
static_tensorrt = False
git_version = 'c084391bae77d86529486cf2bfcca72f84d44232'
torch_version = '1.7.1+cu110'
torch_git_version = '57bffc3a8e4fee0cce31e1ff1f662ccf7b16db57'
GLIBCXX_USE_CXX11_ABI = False

running cpp_test
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: Config value 'nonccl' is not defined in any .rc file
INFO: Invocation ID: a76c93e1-94b4-41cc-9c3e-f317384dc613
Traceback (most recent call last):
  File "setup.py", line 151, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 107, in run
    self.cpp_run()
  File "setup.py", line 91, in cpp_run
    build.test()
  File "/disc/BladeDISC/pytorch_blade/bazel_build.py", line 282, in test
    subprocess.check_call(test_cmd, shell=True, env=env, executable="/bin/bash")
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -e; set -o pipefail;  source .bazel_pyenv/bin/activate; bazel test --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env BAZEL_LINKLIBS=-lstdc++ --action_env CC=/usr/bin/gcc --action_env CXX=/usr/bin/g++ --action_env DISC_FOREIGN_MAKE_JOBS=32 --copt=-DPYTORCH_VERSION_STRING=\"1.7.1+cu110\" --copt=-DPYTORCH_MAJOR_VERSION=1 --copt=-DPYTORCH_MINOR_VERSION=7 --copt=-DTORCH_BLADE_CUDA_VERSION=11.0 --action_env TORCH_BLADE_TORCH_INSTALL_PATH=/usr/local/lib/python3.8/dist-packages/torch --copt=-DPYBIND11_COMPILER_TYPE=\"_gcc\" --copt=-DPYBIND11_STDLIB=\"_libstdcpp\" --copt=-DPYBIND11_BUILD_ABI=\"_cxxabi1011\" --config=torch_debug --config=torch_tensorrt --action_env TENSORRT_INSTALL_PATH=/usr/local/TensorRT/ --action_env NVCC=/usr/local/cuda//bin/nvcc --config=torch_cxx11abi_0 --config=torch_cuda   //tests/mhlo/... //pytorch_blade:torch_blade_test_suite //tests/torch-disc-pdll/tests/... //tests/torchscript/...' returned non-zero exit status 2.

**Comment by tanyokwok** [comment]
@johnzlli Do you have initialized and updated your submodule?

**Comment by johnzlli** [comment]
> @johnzlli Do you have initialized and updated your submodule?

Sorry, it's my fault. It's OK now.
